       double precision N_AVO   ! Avogadro constant = N_AVO * 1.E23 / mol
       PARAMETER (N_AVO = 6.0221367d0)

       double precision ALPHA   ! fine structure constant
       PARAMETER (ALPHA = 1.d0/137.0359895d0)

       double precision PI
       PARAMETER (PI = 3.14159 26535 89793 23846 d0)

       double precision AMU  ! atomic mass unit in MeV
       PARAMETER (AMU = 931.49432d0)

       double precision  EMASS  ! electron mass in MeV
       PARAMETER (EMASS = 0.51099906d0)

       double precision ECHARGE ! electron charge = ECHARGE * 1.E-19 As
       PARAMETER (ECHARGE = 1.60217733d0)

       double precision ECHARGE2 ! ECHARGE**2 in eV * Angstroem
       PARAMETER (ECHARGE2 = 14.399652d0)

       double precision EULER ! Euler's constant
       PARAMETER (EULER = 0.577215664901532861d0)

       double precision CLIGHT ! Speed of light in cm/ns
       PARAMETER (CLIGHT = 29.9792458d0)

