*-----------------------------------------------------------------------

      subroutine pr(nstor,k)
c
c      this is a diagnostic routine which is called from various locatio
c         in the geometry package.
c      additional calls to pr are generated by setting idbg non-zero.
c
c     the amount of data printed depends on the value of k.
c     output produced can be voluminous  - exert caution in using this o
c      do not use it during normal execution of  a problem.
c
      implicit real*8 (a-h,o-z)
      real*8 xb,wb,wp,xp,rin,rout,pinf,dist
      common/parem/xb(3),wb(3),wp(3),xp(3),rin,rout,pinf,dist,ir,idbg ,
     1             irprim,nasc,lsurf,nbo,lri,lro,kloop,loop,itype,noa
!$OMP THREADPRIVATE(/parem/)
      common/gomloc/ kma,kfpd,klcr,knbd,kior,kriz,krcz,kmiz,kmcz,kkr1,
     1 kkr2,knsr,kvol,nadd,ldata,ltma,lfpd,numr,irtru,numb,nir,kbiz,kbcz
!$OMP THREADPRIVATE(/gomloc/)
      common /dbg/ n,num,locat,isave,inext,irp,smin,inex
!$OMP THREADPRIVATE(/dbg/)
      common/repeat/ jp(20)
      common/arar/nby,nlev,nar,nq,iaw,iay,nf,nx1(3)
!$OMP THREADPRIVATE(/arar/)
      common/tape/intt,iot,iout,iou2,idm(4),ioe
!$OMP THREADPRIVATE(/tape/)
      dimension kloc(23),nstor(*)
      parameter ( ispcd = 2 )
      if(idbg.eq.0.and.nar.gt.0) call dipr(nstor,jp,1)
      if(idbg.ne.0) call dipr(nstor,jp,-1)
      if(idbg.gt.1) call errtra

      write(iot ,50) k,xb,wb
   50 format( 3h pr,i5,7h x,y,z ,1p,3d15.8,6h u,v,w ,1p,3d15.8 )

      write(iot ,100) ir,irprim,nasc,lsurf,nbo,lri,lro,kloop,loop,itype,
     1             n,num,locat,isave,inext,irp,inex,ldata,irtru,k,
     2             rin,rout,smin,dist
  100 format(4x,2hir,6x,6hirprim,5x,4hnasc,6x,5hlsurf,6x,3hnbo,6x,3hlri
     1,7x,3hlro,7x,5hkloop,5x,4hloop,5x,5hitype/i5,9i10,/1h0,4x,1hn,7x,
     2 3hnum,5x,5hlocat,5x,5hisave,6x,5hinext,6x,3hirp,6x,4hinex,5x,
     3 5hldata,6x,5hirtru,7x,1hk/i5, 9i10,/1h0,5x,3hrin,11x,4hrout,
     4 10x,4hsmin,10x,4hdist /1p,4d15.7// )

      if(k.ne.1.and.k.ne.8) return
      write(iot ,150) kma,kfpd,klcr,knbd,kior,kriz,krcz,kmiz,kmcz,kkr1, !FURUTA
     1 kkr2,knsr,kvol,nadd,ldata,ltma,lfpd,numr,irtru,numb,nir          !FURUTA
  150 format(15h0  gomloc array/ (5x,10i10))
      write(iot ,60 ) ltma
   60 format(//,23x,   9hma  array,i6,7h values,//)
      krf    = kfpd-1
      i1     = 1
      i2     = 7
      do 500 i=kma,krf,7
      l      = i+6
      write(iot ,70)i1,(nstor(j),j=i,l),i2
      i1     = i1+7
500   i2     = i2+7
   70 format( i6, i10, 6i6, i10  )
      krf    = klcr-1
      write(iot ,80) (dset(nstor(i)),i=kfpd,krf,ispcd)
   80 format(1h0//20x,3hfpd/(5x,1p,8d15.5 ))
      krf    = knsr+numr-1
      write(iot ,85) (nstor(i),i=klcr,krf)
   85 format(1h0//18x,6hothers/(5x,16i6 ))
      krf    = kvol-1+nir*ispcd
      write(iot ,90) (dset(nstor(i)),i=kvol,krf,ispcd)
   90 format(1h0//18x,14hregion volumes /(5x,1p,8d15.5))
      return
      end
c         morse 89  fort 77  (ggx)   2119t!! call dlowp (axc,4,az,icon)
c

