************************************************************************
*                                                                      *
*     'param01.inc'                                                    *
*                                                                      *
*                                                                      *
************************************************************************

      integer ::  mxpa1, mxfnm, mnrho, nnuc, maxpt, maxnt, maxcntr

*----------------------------------------------------------------------*

      parameter ( mxpa1 = 200 )

      parameter ( mxfnm = 50  )
      parameter ( mnrho = 200 )

      parameter ( nnuc  = 3436 )
      parameter ( maxpt = 136, maxnt = 236 )

      parameter ( mxpart = 100 )

      parameter ( maxcntr= 23 ) ! maximum of [counter] parameters
      parameter ( mxcntprt = 20 ) ! maximum of part parameter in [counter]

*-----------------------------------------------------------------------
