
      integer nuclinmax, nuclpumax, maxchain, chainmax
      parameter ( nuclinmax =    100 )
      parameter ( nuclpumax =   1000 )
      parameter ( maxchain =      23 )
      parameter ( chainmax =    4050 )

      integer rimax1, rimax2
      parameter ( rimax1   =    4000 )
      parameter ( rimax2   =   20000 )

      integer,parameter :: nirp = 997   ! read from incident particles
      integer,parameter :: niws = 998   ! read from work souce section
      integer,parameter :: noms = 999   ! write multi-source subsection
